//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmEdificios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edificios
    {
        public int IdEdificio { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public short IdBarrioCABA { get; set; }
        public string CodPostal { get; set; }
        public short CantPisos { get; set; }
        public short CantDptos { get; set; }
        public short CantCocheras { get; set; }
        public short AnioCreacion { get; set; }
        public string Amenities { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public string Comentarios { get; set; }
    
        public virtual BarriosCABA BarriosCABA { get; set; }
    }
}
