INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Agronomía' , 'Comuna 15')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Almagro' , 'Comuna 5')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Balvanera' , 'Comuna 3')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Barracas' , 'Comuna 4')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Belgrano' , 'Comuna 13')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Boedo' , 'Comuna 5')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Caballito' , 'Comuna 6')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Chacarita' , 'Comuna 15')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Coghlan' , 'Comuna 12')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Colegiales' , 'Comuna 13')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Constitución' , 'Comuna 1')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Flores' , 'Comuna 7')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Floresta' , 'Comuna 10')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('La Boca' , 'Comuna 4')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('La Paternal' , 'Comuna 15')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Liniers' , 'Comuna 9')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Mataderos' , 'Comuna 9')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Monserrat' , 'Comuna 1')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Monte Castro' , 'Comuna 10')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Nueva Pompeya' , 'Comuna 4')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Núñez' , 'Comuna 13')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Palermo' , 'Comuna 14')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Parque Avellaneda' , 'Comuna 9')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Parque Chacabuco' , 'Comuna 7')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Parque Chas' , 'Comuna 15')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Parque Patricios' , 'Comuna 4')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Puerto Madero' , 'Comuna 1')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Recoleta' , 'Comuna 2')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Retiro' , 'Comuna 1')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Saavedra' , 'Comuna 12')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('San Cristóbal' , 'Comuna 3')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('San Nicolás' , 'Comuna 1')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('San Telmo' , 'Comuna 1')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Vélez Sársfield' , 'Comuna 10')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Versalles' , 'Comuna 10')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Crespo' , 'Comuna 15')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa del Parque' , 'Comuna 11')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Devoto' , 'Comuna 11')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Gral. Mitre' , 'Comuna 11')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Lugano' , 'Comuna 8')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Luro' , 'Comuna 10')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Ortúzar' , 'Comuna 15')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Pueyrredón' , 'Comuna 12')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Real' , 'Comuna 10')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Riachuelo' , 'Comuna 8')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Santa Rita' , 'Comuna 11')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Soldati' , 'Comuna 8')
INSERT INTO BarriosCABA (Nombre, Comuna) VALUES ('Villa Urquiza' , 'Comuna 12')